### ISSUE TITLE
Import commit history

### ISSUE THREAD

**Issue by 1ec5** [kennykb/osm-shields#1]
Thanks for reviving this project – I hope it succeeds where previous efforts were unsuccessful. Would it be possible to import [Phil Gold’s original shield renderer](https://launchpad.net/osm-shields)’s commit history? Multiple people contributed to the SVG templates. Although that work is in the public domain and doesn’t technically need to be credit, it would be nice to give those folks credit and potentially involve them in the project going forward.

**Comment by kennykb** [comment]
Thanks for noticing!

A few questions/remarks:

(1) Do you know if there is a way to transfer a project from Bazaar to Git (or, more specifically, from Launchpad to Github)?  It's not as simple as doing a clone of a Git repo.

(2) I think that the change history would be of little value in reconstructing contributor acknowledgments; Phil! didn't mention contributors in his log messages when he added templates. The only contributors that I can identify, besides Phil and RIchard, are you and Toby Murray, because the two of you submitted your changes as branches to be merged. Without paying Launchpad for support, I can't even access closed tickets to see if there are clues there!

I'll be happy to add you and Toby to the acknowledgments on the project pages. I'm leaving this ticket open until I actually do that. Sorry that you were left out on the first attempt; I wasn't meaning to discount your contributions!

**Comment by 1ec5** [comment]
> The only contributors that I can identify, besides Phil and RIchard, are you and Toby Murray, because the two of you submitted your changes as branches to be merged.

Heh, I had remembered that people had contributed but totally forgot that I had done so too. 😄

> Without paying Launchpad for support, I can't even access closed tickets to see if there are clues there!

Wow, I didn’t realize that was closed off. I thought there just weren’t any closed issues so far. Yeah, it sounds like more trouble than it’s worth; a simple attribution would be totally fine by me.

**Comment by kennykb** [comment]
Added an ACKNOWLEDGMENTS.md file, with text repeated in LICENSE.html, giving an overview of the lost-history situation, as requested. Closing this issue.
